'use strict';

const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { execFileSync } = require('node:child_process');

const script = path.join(__dirname, 'connections-report');
const workflowDirectory = path.resolve(__dirname, '..');
const groupId = '123e4567-e89b-42d3-a456-426614174999';
const reportPath = path.join(workflowDirectory, 'reports', `connections-report-${groupId}.md`);

function section(report, heading, nextHeading) {
  const start = report.indexOf(`## ${heading}`);
  const end = report.indexOf(`## ${nextHeading}`, start + 1);
  expect(start).toBeGreaterThanOrEqual(0);
  expect(end).toBeGreaterThan(start);
  return report.slice(start, end);
}

afterEach(() => {
  fs.rmSync(reportPath, { force: true });
});

test('generates current onboarding contracts and a prompted generic fallback', () => {
  const fakeBin = fs.mkdtempSync(path.join(os.tmpdir(), 'connections-report-test-'));
  const fakeGsc = path.join(fakeBin, 'gsc');
  fs.writeFileSync(fakeGsc, '#!/bin/sh\necho \'{"group":{"dividers":["Agents"]}}\'\n', { mode: 0o700 });

  try {
    const output = execFileSync(script, ['--group-id', groupId], {
      encoding: 'utf8',
      env: { ...process.env, PATH: `${fakeBin}:${process.env.PATH}` },
    });
    expect(output).toContain(`connections-report-${groupId}.md`);

    const report = fs.readFileSync(reportPath, 'utf8');
    expect(report).toContain('Generated by workflows/agent-collaboration/scripts/connections-report');

    const claude = section(report, 'Claude Code', 'Codex');
    expect(claude).toContain('--timeout 720h');
    expect(claude).not.toContain('"type":"gitsense.buddy.ready"');

    const codex = section(report, 'Codex', 'Pi');
    expect(codex).toContain('CODEX_THREAD_ID is required');
    expect(codex).toContain('codex queue --thread');
    expect(codex).not.toContain('"type":"gitsense.buddy.ready"');
    expect(codex).not.toContain('codex_thread_id: <parent-codex-thread>');

    const pi = section(report, 'Pi', 'Other agent');
    expect(pi).toContain('\\"type\\":\\"gitsense.buddy.ready\\"');

    const generic = report.slice(report.indexOf('## Other agent'));
    expect(generic).toContain('--buddy-prompt');
    expect(generic).toContain('The created Buddy must not run');
    expect(generic).toContain('\\"type\\":\\"gitsense.buddy.ready\\"');
  } finally {
    fs.rmSync(fakeBin, { recursive: true, force: true });
  }
});

test('documents ordered Codex delivery recovery and acknowledgement-free onboarding', () => {
  const common = fs.readFileSync(path.join(workflowDirectory, 'buddy-prompt.md'), 'utf8');
  const codex = fs.readFileSync(path.join(workflowDirectory, 'buddy-instructions', 'codex.md'), 'utf8');

  expect(common).toContain('Valid readiness completes onboarding; do not send an ACK');
  expect(common).not.toContain('GSC_BUDDY_ACK');
  expect(codex.indexOf('gsc inform')).toBeLessThan(codex.indexOf('codex queue'));
  expect(codex).toContain('If `gsc inform` succeeds but `codex queue` fails');
  expect(codex).toContain('Do not send it again. Retry only `codex queue`');
});
