/*
 * GitSense Chat - Minified Distribution File
 *
 * This JavaScript file is part of the minified distribution of GitSense Chat.
 * It has been optimized (minified) for performance and efficient delivery.
 *
 * This software is permitted for internal use and modification.
 * Copying for profit or redistribution is strictly not permitted.
 *
 * The Fair License, which formalizes these terms, will be adopted as the official license in the future.
 * Once finalized, the unminified source code will be freely available for internal use for non-
 * commercial purposes.
 *
 * This software may not be used to develop or enhance any product or service that competes
 * directly or indirectly with GitSense Chat without explicit permission.
 *
 * Copyright (c) 2026 GitSense. All rights reserved.
 */

let FullMetaErrorHandler=require("../shared/FullMetaErrorHandler");class MetaRawResultProcessor{constructor(){this.errorHandler=new FullMetaErrorHandler}mergeRawResults(r,a,t){if(!Array.isArray(r)||0===r.length)return[];if(!Array.isArray(t)||0===t.length)return[];var e,n=new Map;for(e of r[0]){var s=e.chats_id;n.has(s)||n.set(s,{chats_id:s,repo:e.groups_name,branch:"branch"===e.chats_meta_ref_context_type?e.chats_meta_ref_name:"N/A",path:e.chats_meta_git_path,language:e.chats_meta_language,metadata:{}}),this._extractAndMergeMetadata(n.get(s).metadata,e,a,t[0])}for(let e=1;e<r.length;e++)for(var o of r[e]){var i=o.chats_id;n.has(i)&&this._extractAndMergeMetadata(n.get(i).metadata,o,a,t[e])}return Array.from(n.values())}_extractAndMergeMetadata(e,r,a,t){for(var n of a){var s;n.analyzerId===t&&void 0!==r[s="meta_"+n.field]&&(e[n.analyzerId+"|"+n.field]=r[s])}}formatPretty(n,s,o,i){if(0===n.length)return"# Metadata Insights Analysis\n\nNo files matched the specified criteria.\n";let l=new Map,f=new Map,p=new Map,c=o&&o.isCustom,d=new Map,h=new Map;if(c&&o){let a=new Map,t=new Map;Object.entries(o.repo).forEach(([e,{name:r}])=>{l.set(r,"R"+e),a.set(r,e)}),Object.entries(o.branch).forEach(([e,{name:r}])=>{f.set(r,"B"+e),t.set(r,e)}),Object.entries(o.analyzer).forEach(([e,{name:r,description:a}])=>{d.set(r,"A"+e),h.set("A"+e,{name:r,description:a})}),Object.entries(o.field).forEach(([,{name:e,analyzerId:r,fieldId:a}])=>{var t=o.analyzer[r];if(!t)throw this.errorHandler.createInvalidSyntaxError(`Internal error: Analyzer ID '${r}' from field-mapping not found in analyzer-mapping.`);r=t.name+"|"+e;p.set(r,"F"+a)});for(var e of n){if(e.repo&&!a.has(e.repo))throw this.errorHandler.createInvalidSyntaxError(`Missing mapping for repository: ${e.repo}. All repositories in the result set must be mapped.`);if(e.branch&&!t.has(e.branch))throw this.errorHandler.createInvalidSyntaxError(`Missing mapping for branch: ${e.branch}. All branches in the result set must be mapped.`)}}else{let e=1,r=1,a=1,t=1;for(var m of n)m.repo&&!l.has(m.repo)&&l.set(m.repo,"R"+e++),m.branch&&!f.has(m.branch)&&f.set(m.branch,"B"+r++);var y,u;for(y of new Set(s.map(e=>e.analyzerId)))d.has(y)||d.set(y,"A"+a++);for(u of s){var g=u.analyzerId+"|"+u.field;p.has(g)||p.set(g,"F"+t++)}}let b="# Metadata Insights Analysis\n\n";b+="## Repository Reference\n",Array.from(l.entries()).sort((e,r)=>e[1].localeCompare(r[1])).forEach(([e,r])=>{var a=r.substring(1),a=c?o.repo[a]:null,a=a&&a.description?" - "+a.description:"";b+=`- **${r}**: ${e}${a}
`}),b+="\n## Branch Reference\n",Array.from(f.entries()).sort((e,r)=>e[1].localeCompare(r[1])).forEach(([e,r])=>{var a=c?Object.values(o.branch).find(e=>"B"+e.id===r):null,a=a&&a.description?" - "+a.description:"";b+=`- **${r}**: ${e}${a}
`}),b+="\n## Analyzer Reference\n",Array.from(d.entries()).sort((e,r)=>e[1].localeCompare(r[1])).forEach(([e,r])=>{var a=c?h.get(r):null,a=a&&a.description?" - "+a.description:"";b+=`- **${r}**: ${e}${a}
`}),b+="\n## Field Reference\n",Array.from(p.entries()).sort((e,r)=>e[1].localeCompare(r[1])).forEach(([r,e])=>{let a=s.find(e=>e.analyzerId+"|"+e.field===r);var t=d.get(a.analyzerId)||"N/A",n=c?Object.values(o.field).find(e=>e.name===a.field&&o.analyzer[e.analyzerId].name===a.analyzerId):null,n=(n||a).description;b+=`- **${e}**: ${a.field} (${a.type}) - ${n} Extracted by ${t}.
`}),b+="\n## Data (File Metadata)\n";var a,r=["Repo","Branch","File","Language","Chat ID"],t=["------","--------","------","---------","-------"],A=Array.from(p.values());r.push(...A),t.push(...A.map(()=>"---")),b=(b+=`| ${r.join(" | ")} |
`)+`| ${t.join(" | ")} |
`;for(a of n){var v=l.get(a.repo)||"N/A",_=f.get(a.branch)||"N/A",M=[v,_,a.path,a.language||"N/A",a.chats_id];if(c&&("N/A"===v||"N/A"===_))throw this.errorHandler.createInvalidSyntaxError(`Internal error: Result entity missing mapping. Repo: ${a.repo}, Branch: `+a.branch);for(let[r,e]of p.entries()){var I,z=a.metadata[r];let e="N/A";null!=z&&(I=s.find(e=>e.analyzerId+"|"+e.field===r),e="boolean"===I.type?1===z||!0===z||"1"===z?"true":"false":"number"===I.type?Number(z):"string"===I.type||"array"===I.type?`"${z.toString().replace(/"/g,'\\"')}"`:z.toString()),M.push(e)}b+=`| ${M.join(" | ")} |
`}return b+="\n\n## Analyzer Metadata\n",Array.from(d.entries()).sort((e,r)=>e[1].localeCompare(r[1])).forEach(([e,r])=>{var a=i[e]||{},t=(console.log(a),a.label||e),a=a.version||"1.0.0";b=(b+=`- **${r}**: ${e}
`)+`  - Label: ${t}
`+`  - Version: ${a}
`}),b+="\n"}formatManifest(n,o,t,s){let i=new Map,l=new Map,f=new Map,p=new Map;var c,d;if(t&&t.isCustom&&t)Object.entries(t.repo).forEach(([e,{name:r}])=>i.set(r,"R"+e)),Object.entries(t.branch).forEach(([e,{name:r}])=>l.set(r,"B"+e)),Object.entries(t.analyzer).forEach(([e,{name:r}])=>f.set(r,"A"+e)),Object.entries(t.field).forEach(([e,{name:r,analyzerId:a}])=>{var a=t.analyzer[a];a&&(a=a.name,p.set(a+"|"+r,"F"+e.split("|")[1]))});else{let e=0,r=0,a=0,t=0;for(var h of n)h.repo&&!i.has(h.repo)&&i.set(h.repo,"R"+e++),h.branch&&!l.has(h.branch)&&l.set(h.branch,"B"+r++);for(c of new Set(o.map(e=>e.analyzerId)))f.has(c)||f.set(c,"A"+a++);for(d of o){var m=d.analyzerId+"|"+d.field;p.has(m)||p.set(m,"F"+t++)}}var e=Array.from(i.entries()).map(([e,r])=>({ref:r,name:e})),r=Array.from(l.entries()).map(([e,r])=>({ref:r,name:e})),a=Array.from(f.entries()).map(([e,r])=>{var a=s[e]||{};return{ref:r,id:e,name:a.label||e,description:a.description||"",version:a.version||"1.0.0"}}),y=Array.from(p.entries()).map(([e,r])=>{let[a,t]=e.split("|");e=o.find(e=>e.analyzerId===a&&e.field===t);return{ref:r,analyzer_ref:f.get(a)||"N/A",name:t,display_name:t.replace(/_/g," ").replace(/\w\S*/g,e=>e.charAt(0).toUpperCase()+e.substr(1).toLowerCase()),type:e?e.type:"string",description:e?e.description:""}}),n=n.map(e=>{var t={repo_ref:i.get(e.repo)||"N/A",branch_ref:l.get(e.branch)||"N/A",file_path:e.path,language:e.language,chat_id:e.chats_id,fields:{}};for(let[r,a]of p.entries()){var n=e.metadata[r];if(null!=n){var s=o.find(e=>e.analyzerId+"|"+e.field===r);if(s&&"number"===s.type)t.fields[a]=Number(n);else if(s&&"boolean"===s.type)t.fields[a]=1===n||!0===n||"1"===n;else if(s&&"array"===s.type)try{t.fields[a]="string"==typeof n?JSON.parse(n):n}catch(e){t.fields[a]=n}else t.fields[a]=n}}return t}),e={schema_version:"1.0",generated_at:(new Date).toISOString(),repositories:e,branches:r,analyzers:a,fields:y,data:n};return JSON.stringify(e,null,2)}formatFinalResponse(e,r,a,t){return{status:"success",data:{query:r,searchCriteria:a,results:e,totalResultsReturned:t,pagination:{currentPage:1,totalPages:0<t?1:0,totalResults:t,resultsPerPage:t}}}}}module.exports=MetaRawResultProcessor;
