/*
 * GitSense Chat - Minified Distribution File
 *
 * This JavaScript file is part of the minified distribution of GitSense Chat.
 * It has been optimized (minified) for performance and efficient delivery.
 *
 * Licensed under the Fair Core License, Version 1.0 (FCL-1.0-ALv2).
 * https://faircode.io
 *
 * You may use, modify, and run this software for internal, non-commercial
 * purposes including personal projects, team workflows, and self-hosted
 * deployments. You may not use this software to build or operate a product
 * or service that competes directly or indirectly with GitSense Chat.
 * Redistribution or resale is not permitted.
 *
 * Copyright (c) 2026 GitSense. All rights reserved.
 *
 * For licensing inquiries, internal-use exceptions, or business use,
 * contact sales@gitsense.com
 */

let FullMetaErrorHandler=require("../shared/FullMetaErrorHandler");class MetaRawResultProcessor{constructor(){this.errorHandler=new FullMetaErrorHandler}mergeRawResults(r,a,t){if(!Array.isArray(r)||0===r.length)return[];if(!Array.isArray(t)||0===t.length)return[];var e,n=new Map;for(e of r[0]){var s=e.chats_id;n.has(s)||n.set(s,{chats_id:s,repo:e.groups_name,branch:"branch"===e.chats_meta_ref_context_type?e.chats_meta_ref_name:"N/A",path:e.chats_meta_git_path,language:e.chats_meta_language,metadata:{}}),this._extractAndMergeMetadata(n.get(s).metadata,e,a,t[0])}for(let e=1;e<r.length;e++)for(var i of r[e]){var l=i.chats_id;n.has(l)&&this._extractAndMergeMetadata(n.get(l).metadata,i,a,t[e])}return Array.from(n.values())}_extractAndMergeMetadata(e,r,a,t){for(var n of a){var s;n.analyzerId===t&&void 0!==r[s="meta_"+n.field]&&(e[n.analyzerId+"|"+n.field]=r[s])}}formatPretty(n,s,i,l){if(0===n.length)return"# Metadata Insights Analysis\n\nNo files matched the specified criteria.\n";var o,f;let d=new Map,p=new Map,c=new Map,h=i&&i.isCustom,m=new Map,y=new Map;if(h&&i){let a=new Map,t=new Map;Object.entries(i.repo).forEach(([e,{name:r}])=>{d.set(r,"R"+e),a.set(r,e)}),Object.entries(i.branch).forEach(([e,{name:r}])=>{p.set(r,"B"+e),t.set(r,e)}),Object.entries(i.analyzer).forEach(([e,{name:r,description:a}])=>{m.set(r,"A"+e),y.set("A"+e,{name:r,description:a})}),Object.entries(i.field).forEach(([,{name:e,analyzerId:r,fieldId:a}])=>{var t=i.analyzer[r];if(!t)throw this.errorHandler.createInvalidSyntaxError(`Internal error: Analyzer ID '${r}' from field-mapping not found in analyzer-mapping.`);r=t.name+"|"+e;c.set(r,"F"+a)});for(var e of n){if(e.repo&&!a.has(e.repo))throw this.errorHandler.createInvalidSyntaxError(`Missing mapping for repository: ${e.repo}. All repositories in the result set must be mapped.`);if(e.branch&&!t.has(e.branch))throw this.errorHandler.createInvalidSyntaxError(`Missing mapping for branch: ${e.branch}. All branches in the result set must be mapped.`)}}else{let e=1,r=1,a=1,t=1;for(var u of n)u.repo&&!d.has(u.repo)&&d.set(u.repo,"R"+e++),u.branch&&!p.has(u.branch)&&p.set(u.branch,"B"+r++);for(o of new Set(s.map(e=>e.analyzerId)))m.has(o)||m.set(o,"A"+a++);for(f of s){var g=f.analyzerId+"|"+f.field;c.has(g)||c.set(g,"F"+t++)}}let b="# Metadata Insights Analysis\n\n";b+="## Repository Reference\n",Array.from(d.entries()).sort((e,r)=>e[1].localeCompare(r[1])).forEach(([e,r])=>{var a=r.substring(1),a=h?i.repo[a]:null,a=a&&a.description?" - "+a.description:"";b+=`- **${r}**: ${e}${a}
`}),b+="\n## Branch Reference\n",Array.from(p.entries()).sort((e,r)=>e[1].localeCompare(r[1])).forEach(([e,r])=>{var a=h?Object.values(i.branch).find(e=>"B"+e.id===r):null,a=a&&a.description?" - "+a.description:"";b+=`- **${r}**: ${e}${a}
`}),b+="\n## Analyzer Reference\n",Array.from(m.entries()).sort((e,r)=>e[1].localeCompare(r[1])).forEach(([e,r])=>{var a=h?y.get(r):null,a=a&&a.description?" - "+a.description:"";b+=`- **${r}**: ${e}${a}
`}),b+="\n## Field Reference\n",Array.from(c.entries()).sort((e,r)=>e[1].localeCompare(r[1])).forEach(([r,e])=>{let a=s.find(e=>e.analyzerId+"|"+e.field===r);var t=m.get(a.analyzerId)||"N/A",n=h?Object.values(i.field).find(e=>e.name===a.field&&i.analyzer[e.analyzerId].name===a.analyzerId):null,n=(n||a).description;b+=`- **${e}**: ${a.field} (${a.type}) - ${n} Extracted by ${t}.
`}),b+="\n## Data (File Metadata)\n";var a,r=["Repo","Branch","File","Language","Chat ID"],t=["------","--------","------","---------","-------"],v=Array.from(c.values());r.push(...v),t.push(...v.map(()=>"---")),b=(b+=`| ${r.join(" | ")} |
`)+`| ${t.join(" | ")} |
`;for(a of n){var A=d.get(a.repo)||"N/A",_=p.get(a.branch)||"N/A",M=[A,_,a.path,a.language||"N/A",a.chats_id];if(h&&("N/A"===A||"N/A"===_))throw this.errorHandler.createInvalidSyntaxError(`Internal error: Result entity missing mapping. Repo: ${a.repo}, Branch: `+a.branch);for(let[r,e]of c.entries()){var I,z=a.metadata[r];let e="N/A";null!=z&&(I=s.find(e=>e.analyzerId+"|"+e.field===r),e="boolean"===I.type?1===z||!0===z||"1"===z?"true":"false":"number"===I.type?Number(z):"string"===I.type||"array"===I.type?`"${I=z.toString(),I?I.replace(/\\/g,"\\\\").replace(/"/g,'\\"').replace(/\|/g,"\\|").replace(/\n/g," "):""}"`:z.toString()),M.push(e)}b+=`| ${M.join(" | ")} |
`}return b+="\n\n## Analyzer Metadata\n",Array.from(m.entries()).sort((e,r)=>e[1].localeCompare(r[1])).forEach(([e,r])=>{var a=l[e]||{},t=a.label||e,a=a.version||"1.0.0";b=(b+=`- **${r}**: ${e}
`)+`  - Label: ${t}
`+`  - Version: ${a}
`}),b+="\n"}formatManifest(n,i,t,s){let l=new Map,o=new Map,f=new Map,d=new Map;var p,c;if(t&&t.isCustom&&t)Object.entries(t.repo).forEach(([e,{name:r}])=>l.set(r,"R"+e)),Object.entries(t.branch).forEach(([e,{name:r}])=>o.set(r,"B"+e)),Object.entries(t.analyzer).forEach(([e,{name:r}])=>f.set(r,"A"+e)),Object.entries(t.field).forEach(([e,{name:r,analyzerId:a}])=>{var a=t.analyzer[a];a&&(a=a.name,d.set(a+"|"+r,"F"+e.split("|")[1]))});else{let e=0,r=0,a=0,t=0;for(var h of n)h.repo&&!l.has(h.repo)&&l.set(h.repo,"R"+e++),h.branch&&!o.has(h.branch)&&o.set(h.branch,"B"+r++);for(p of new Set(i.map(e=>e.analyzerId)))f.has(p)||f.set(p,"A"+a++);for(c of i){var m=c.analyzerId+"|"+c.field;d.has(m)||d.set(m,"F"+t++)}}var e=Array.from(l.entries()).map(([e,r])=>({ref:r,name:e})),r=Array.from(o.entries()).map(([e,r])=>({ref:r,name:e})),a=Array.from(f.entries()).map(([e,r])=>{var a=s[e]||{};return{ref:r,id:e,name:a.label||e,description:a.description||"",version:a.version||"1.0.0"}}),y=Array.from(d.entries()).map(([e,r])=>{let[a,t]=e.split("|");e=i.find(e=>e.analyzerId===a&&e.field===t);return{ref:r,analyzer_ref:f.get(a)||"N/A",name:t,display_name:t.replace(/_/g," ").replace(/\w\S*/g,e=>e.charAt(0).toUpperCase()+e.substr(1).toLowerCase()),type:e?e.type:"string",description:e?e.description:""}}),n=n.map(e=>{var t={repo_ref:l.get(e.repo)||"N/A",branch_ref:o.get(e.branch)||"N/A",file_path:e.path,language:e.language,chat_id:e.chats_id,fields:{}};for(let[r,a]of d.entries()){var n=e.metadata[r];if(null!=n){var s=i.find(e=>e.analyzerId+"|"+e.field===r);if(s&&"number"===s.type)t.fields[a]=Number(n);else if(s&&"boolean"===s.type)t.fields[a]=1===n||!0===n||"1"===n;else if(s&&"array"===s.type)try{t.fields[a]="string"==typeof n?JSON.parse(n):n}catch(e){t.fields[a]=n}else t.fields[a]=n}}for(let[r,e]of d.entries()){var a=i.find(e=>e.analyzerId+"|"+e.field===r);a&&void 0===t.fields[e]&&("file_path"===a.field?t.fields[e]=t.file_path:"chat_id"===a.field&&(t.fields[e]=Number(t.chat_id)))}return t}),e={schema_version:"1.0",generated_at:(new Date).toISOString(),repositories:e,branches:r,analyzers:a,fields:y,data:n};return JSON.stringify(e,null,2)}formatFinalResponse(e,r,a,t){return{status:"success",data:{query:r,searchCriteria:a,results:e,totalResultsReturned:t,pagination:{currentPage:1,totalPages:0<t?1:0,totalResults:t,resultsPerPage:t}}}}}module.exports=MetaRawResultProcessor;
