/*
 * GitSense Chat - Minified Distribution File
 *
 * This JavaScript file is part of the minified distribution of GitSense Chat.
 * It has been optimized (minified) for performance and efficient delivery.
 *
 * This software is permitted for internal use and modification.
 * Copying for profit or redistribution is strictly not permitted.
 *
 * The Fair License, which formalizes these terms, will be adopted as the official license in the future.
 * Once finalized, the unminified source code will be freely available for internal use for non-
 * commercial purposes.
 *
 * This software may not be used to develop or enhance any product or service that competes
 * directly or indirectly with GitSense Chat without explicit permission.
 *
 * Copyright (c) 2026 GitSense. All rights reserved.
 */

let{CodeBlockUtils,DomUtils,MessageUtils,PatchUtils}=require("@gitsense/gsc-utils"),BlockMapService=require("../../services/BlockMapService"),createRegenerateRequestMessage=require("../../utils/PatchRegenerationUtils").createRegenerateRequestMessage,QuickChatButtons=require("../../Dependencies").QuickChatButtons,ChangePreviewModal=require("../modals/ChangePreviewModal"),generatePatchedHeaderText=require("../modals/ChangePreviewModal/utils/headerGenerator").generatePatchedHeaderText,h=DomUtils.h;async function handlePatch(b,r,D,w){if(!(b&&null!=b.message&&r&&D&&D.codeBlockService&&D.chat))return console.error("handlePatch: Missing message, contentBody, codeBlockService, or chat in context."),!1;if("conversation-assistant"===D.chat.type)return!1;if("fix-patch"===D.chat.type)return!1;var e=CodeBlockUtils.processCodeBlocks(b.message,{silent:!0}).blocks,a=e.filter((e,t)=>{if("patch"===e.type)return e.index=t,e});if(0===a.length)return!1;var o=r.querySelectorAll("pre");for(let e=0;e<o.length;e++){var n=o[e],c=n.innerText.replace(/^\w+\s+# Patch Metadata/,"# Patch Metadata");let t=PatchUtils.extractPatchMetadata(c);if(t["Source-Block-UUID"]||t["Target-Block-UUID"]){c=a.find(e=>e.metadata["Source-Block-UUID"]===t["Source-Block-UUID"]&&e.metadata["Target-Block-UUID"]===t["Target-Block-UUID"]);if(!c)return console.error("Unable to determine the patch block that the PRE element belongs to.",n),!1;var l=h.createDiv({style:{display:"none"}});n.insertAdjacentElement("afterend",l),c.controlsContainer=l}}let T=new BlockMapService,I=(T.updateFromChat(D.chat),T.getBlocksImmutable());a.forEach(c=>{try{var a=c.controlsContainer,e=c.metadata["Target-Block-UUID"]||null;if(e?T.getBlockInfo(e):null)_showPatchError(a,`This patch cannot be used because the UUID ${e} is not unique.`,b,c,D,w,"Target UUID not Unique");else{var t=c.metadata["Source-Block-UUID"]||"Unknown",l=CodeBlockUtils.getLineage(t,I),o=l.findIndex(e=>e.header?.["Block-UUID"]);if(-1===o){let o=[c,...l],r=new Set,n="";_showPatchError(a,`
                    <p><strong>This patch cannot be tested because its original source code is missing.</strong></p>
                    <p>To apply a patch, I must first find the complete, original code block it was based on. I traced the history but could not find it in this conversation.</p>
                    
                    <details>
                        <summary><strong>Diagnostic Trace</strong></summary>
                        <pre style="margin-top: 10px; padding: 10px; border-radius: 4px; background-color: #f0f0f0; color: #333;">${o.map((e,t)=>{var a=e.metadata["Target-Block-UUID"];return r.has(a)?"<strong>Loop Detected</strong>":(r.add(a),"Patch Target: "+a+((n=t===o.length-1?e.metadata["Source-Block-UUID"]:"")?`
 Base Source: `+n:""))}).join("\n")}</pre>
                    </details>

                    <p style="margin-top: 15px;">Please add the source with the UUID ${n} to this chat, and I will re-evaluate the patch.</p>
                `,b,c,D,w,"Untestable Patch: Source Code Missing")}else{var i=l[o],s=l[o];let t=s.headerText+"\n\n\n"+s.content;var d="```"+i.language+"\n"+t+"```",p=CodeBlockUtils.processCodeBlocks(d,{silent:!0}).blocks;let r=p[0];for(let e=o-1;0<=e;e--){var g=l[e];if(g.isPatch){var u,m,U,k,x,f=PatchUtils.applyPatch(t,g.content);if(!f.valid)return _showPatchError(a,"Failed to apply patch in lineage chain: "+(f.errors[0]||"Unknown application error"),b,c,D,w,"Patch Chain Application Failed"),!0;t=f.patchedText,u=generatePatchedHeaderText(r.headerText,g.metadata),m="```"+r.language+"\n"+t.trimEnd()+"\n```",U=CodeBlockUtils.processCodeBlocks(m,{silent:!0}).blocks,k=U[0].content.trimEnd(),d="```"+r.language+"\n"+u+"\n\n\n"+k+"\n```",x=CodeBlockUtils.processCodeBlocks(d,{silent:!0}).blocks,r=x[0]}}let n=PatchUtils.applyPatch(t,c.content);if(n.valid)try{var C=h.createDiv({cls:"patch-controls",style:{display:"flex",alignItems:"center",justifyContent:"space-between",marginTop:"5px",marginBottom:"20px",padding:"10px",border:"1px solid #28a745",borderRadius:"4px",backgroundColor:"#eafaf1"}}),v=h.createStrong({text:"Patch Validated",style:{color:"#155724",fontSize:"0.9em"}}),y=h.createLink({text:"Review Full Code",href:"#",style:{textDecoration:"none",fontWeight:"bold",fontSize:"0.9em"},onclick:e=>{e.preventDefault(),ChangePreviewModal.launch(b,r,c,null,D.widget,D.codeBlockService,D.hljs)}}),B=h.createSpan({text:" | ",style:{margin:"0 7px",color:"#155724"}});let o=h.createLink({text:"Copy Full Code",href:"#",style:{textDecoration:"none",fontWeight:"bold",fontSize:"0.9em"},onclick:e=>{e.preventDefault();var e="```"+r.language+"\n"+n.patchedText.trimEnd()+"\n```",e=CodeBlockUtils.extractCodeBlocks(e).blocks,t=PatchUtils.formatCodeBlockHeader(r,c),e=e[0]?.content||"N/A";navigator.clipboard.writeText(t+`


`+e);let a=o.textContent;o.textContent="Copied!",setTimeout(()=>{o.textContent=a},2e3)}});var P=h.createDiv({append:[y,B,o],style:{display:"inline-block"}});C.appendChild(v),C.appendChild(P),a.style.display="block",a.appendChild(C)}catch(e){console.error("Could not create preview for patch:",e)}else _showPatchError(a,"This patch cannot be applied to the source code. "+(n.errors[0]||"Unknown application error"),b,c,D,w,"Patch Application Failed",{patchSource:t,patchContent:c.content,patchSourceBlock:r,foundationBlock:s})}}return!0}catch(e){return console.error(`handlePatch: Unexpected error during validation for message ID ${b.id}:`,e),_showPatchError(r,"Internal error during patch validation: "+e.message,b,c,D,w,"Internal Validation Error"),!0}})}function _showPatchError(e,t,o,r,n,a,c="Patch Error",l=null){var i;e&&e.parentNode?(i=DomUtils.h.createH3({text:c,style:{color:"#721c24",marginTop:"0",fontSize:"16px"}}),t=DomUtils.h.createParagraph({html:t,style:{color:"#721c24"}}),i=DomUtils.h.createDiv({cls:"patch-error-container",append:[i,t],style:{marginTop:"5px",marginBottom:"20px",padding:"15px",paddingBottom:"0px",border:"1px solid #dc3545",borderRadius:"4px",backgroundColor:"#f8d7da"}}),e.style.display=null,e.appendChild(i),"Target UUID not Unique"!==c&&"Internal Validation Error"!==c&&"Untestable Patch: Source Code Missing"!==c&&"Patch Chain Application Failed"!==c&&(DomUtils.h.createH3({text:"Fix Patch",style:{}}),t=DomUtils.h.createParagraph({html:'To fix the patch above or to replace it with the full code, click the button below to start a "Fix Patch Chat".',style:{}}),i=DomUtils.h.createButton({cls:"btn btn-primary regenerate-patch-btn",text:"Fix Patch",style:{marginRight:"5px",marginBottom:"20px"},onclick:()=>{try{var e=DomUtils.h.createDiv({style:{display:"none"}}),t=(document.body.appendChild(e),{type:"fix-patch",params:{patchMessage:o,patchBlock:r,patchContext:l},onDone:()=>{}}),a=new QuickChatButtons([t],n);a.render(e),a.click(t)}catch(e){console.error("Error creating regeneration request message:",e)}}}),c=DomUtils.h.createDiv({append:[t,i],style:{paddingBottom:"10px"}}),e.appendChild(c))):console.error("_showPatchError: Cannot display error, invalid renderTo.")}module.exports={handlePatch:handlePatch};
