/*
 * GitSense Chat - Minified Distribution File
 *
 * This JavaScript file is part of the minified distribution of GitSense Chat.
 * It has been optimized (minified) for performance and efficient delivery.
 *
 * This software is permitted for internal use and modification.
 * Copying for profit or redistribution is strictly not permitted.
 *
 * The Fair License, which formalizes these terms, will be adopted as the official license in the future.
 * Once finalized, the unminified source code will be freely available for internal use for non-
 * commercial purposes.
 *
 * This software may not be used to develop or enhance any product or service that competes
 * directly or indirectly with GitSense Chat without explicit permission.
 *
 * Copyright (c) 2026 GitSense. All rights reserved.
 */

let DomUtils=require("@gitsense/gsc-utils").DomUtils,SVGUtils=require("@gitsense/gsc-utils").SVGUtils,formatVisibilityDuration=require("../../utils/formatUtils").formatVisibilityDuration,FileUtils=require("../../utils/fileUtils");class UIComponents{static renderToggle(e,t){var i=DomUtils.h.createDiv(),a=(i.className="import-data-toggle-container",DomUtils.h.createButton()),r=(a.className="import-data-toggle-option "+("dropzone"===e?"active":""),a.textContent="Drag and Drop",a.addEventListener("click",()=>t("dropzone")),DomUtils.h.createButton());return r.className="import-data-toggle-option "+("snippet"===e?"active":""),r.textContent="Create Text Snippet",r.addEventListener("click",()=>t("snippet")),i.appendChild(a),i.appendChild(r),i}static renderDropzoneArea(t,e,i){var a=DomUtils.h.createDiv();a.className="import-data-dropzone-area";let r=DomUtils.h.createDiv();r.className="import-data-dropzone";var n=SVGUtils.download({style:{height:"55px",width:"55px",fill:"#666",marginBottom:"10px"}}),n=(r.appendChild(n),DomUtils.h.createDiv()),n=(n.className="import-data-dropzone-text",n.textContent="Drag and drop your files here",r.appendChild(n),DomUtils.h.createDiv()),n=(n.className="import-data-dropzone-hint",n.textContent="or click to browse",r.appendChild(n),DomUtils.h.createDiv()),l=(n.className="import-data-limits-indicator",DomUtils.h.createDiv()),o=(l.className="import-data-limit-item",l.innerHTML=`
            <span class="import-data-limit-text">0 / ${i.maxFiles||5} files</span>
        `,DomUtils.h.createDiv()),s=(o.className="import-data-limit-item",o.innerHTML='<span class="import-data-limit-text">-</span>',DomUtils.h.createDiv()),i=(s.className="import-data-limit-item",Math.round((i.maxSize||10485760)/1048576));s.innerHTML=`
            <span class="import-data-limit-text">0 MB / ${i} MB</span>
        `,n.appendChild(l),n.appendChild(o),n.appendChild(s),r.appendChild(n);let p=DomUtils.h.createInput({type:"file",multiple:!0});return p.style.display="none",p.addEventListener("change",()=>t(p.files)),r.addEventListener("click",()=>{p.click()}),r.addEventListener("dragover",e=>{e.preventDefault(),r.classList.add("dragover")}),r.addEventListener("dragleave",e=>{e.preventDefault(),r.classList.remove("dragover")}),r.addEventListener("drop",e=>{e.preventDefault(),r.classList.remove("dragover"),t(e.dataTransfer.files)}),a.appendChild(r),a.appendChild(p),{container:a,fileCountText:l.querySelector(".import-data-limit-text"),fileSizeText:s.querySelector(".import-data-limit-text")}}static renderSnippetArea(e,t){var i=DomUtils.h.createDiv(),a=(i.className="import-data-snippet-area",DomUtils.h.createDiv()),r=(a.className="import-data-form-group",DomUtils.h.createLabel());r.textContent="File Name",a.appendChild(r);let n=DomUtils.h.createInput({type:"text",value:e.filename||"snippet.txt",placeholder:"Enter file name with extension"});n.className="import-data-form-input",a.appendChild(n);r=DomUtils.h.createDiv(),r.className="import-data-form-hint",r.textContent="Include the appropriate file extension for syntax highlighting (e.g., .js, .py, .log)",a.appendChild(r),e=DomUtils.h.createDiv(),e.className="import-data-form-group",r=DomUtils.h.createLabel();r.textContent="Content",e.appendChild(r);let l=DomUtils.h.createTextarea();l.className="import-data-form-textarea",l.placeholder="Paste your code snippet, log output, or any text content here...",e.appendChild(l);r=DomUtils.h.createDiv();r.className="import-data-form-hint",r.textContent="This content will be saved as a single file in your repository. Default filename is snippet.txt if left empty.",e.appendChild(r);let o=()=>{t({filename:n.value.trim(),content:l.value})};return n.addEventListener("blur",()=>{n.value.trim()||(n.value="snippet.txt",o())}),n.addEventListener("input",o),l.addEventListener("input",o),i.appendChild(a),i.appendChild(e),{container:i,filenameInput:n,contentTextarea:l}}static renderRepositoryConfig(e,t){var i=DomUtils.h.createDiv(),a=(i.className="import-data-repo-config",DomUtils.h.createH3({style:{textAlign:"center",marginBottom:"10px"}})),a=(a.textContent="Repository Configuration",i.appendChild(a),DomUtils.h.createP({style:{fontSize:"14px",textAlign:"center"}})),a=(a.className="import-data-repo-config-subtitle",a.textContent="Turn your files into a git repository",i.appendChild(a),DomUtils.h.createDiv()),r=(a.className="import-data-form-group",DomUtils.h.createLabel());r.textContent="Name Prefix (Optional)",a.appendChild(r);let n=DomUtils.h.createInput({type:"text",value:e.namePrefix||"",placeholder:"e.g., my-project"});n.className="import-data-form-input",a.appendChild(n);var r=DomUtils.h.createDiv(),l=(r.className="import-data-repo-name-preview",r.style.cssText=`
            margin-top: 10px;
            padding: 10px;
            background-color: #f8f9fa;
            border-radius: 4px;
            font-family: monospace;
            font-size: 12px;
            color: #333;
        `,DomUtils.h.createSpan());l.textContent="GSC-Dropzone / ",r.appendChild(l);let o=DomUtils.h.createSpan();o.className="import-data-preview-prefix";var l=e.namePrefix||"my-project",l=(o.textContent=l,r.appendChild(o),DomUtils.h.createSpan()),l=(l.textContent="-",r.appendChild(l),DomUtils.h.createSpan()),l=(l.className="import-data-preview-suffix",l.textContent=e.nameSuffix||"a1b2c3d4",l.style.cssText="color: #007bff; font-weight: bold;",r.appendChild(l),a.appendChild(r),DomUtils.h.createDiv());return l.className="import-data-form-hint",l.textContent="This will be your GitSense Chat dropzone repository with a random suffix added. Leave empty to use the default name prefix.",a.appendChild(l),n.addEventListener("input",()=>{var e=n.value.trim();o.textContent=e||"my-project",t({namePrefix:e})}),i.appendChild(a),void 0!==e.visibilityDuration&&0<=e.visibilityDuration&&((r=DomUtils.h.createDiv()).className="import-data-visibility-note",(l=DomUtils.h.createP()).style.margin="0",l.innerHTML=`
                <strong>Note:</strong> Your repository will be visible in the Repositories tree for 
                <strong>${formatVisibilityDuration(e.visibilityDuration)}</strong> 
                after import. After this period, it will be automatically hidden to keep the repository tree organized.
                Please contact your GitSense Chat administrator to update the time limit.
            `,r.appendChild(l),i.appendChild(r)),{container:i,nameInput:n,previewPrefix:o}}static renderFileList(e,i){var a=DomUtils.h.createDiv();if(a.className="import-data-file-list",0===e.length)a.style.display="none";else{var r=DomUtils.h.createH3();r.textContent="Selected Files",a.appendChild(r);let t=DomUtils.h.createDiv();t.className="import-data-file-items",e.forEach(e=>{e=this._createFileItem(e,i);t.appendChild(e)}),a.appendChild(t)}return a}static renderActions(e,t,i,a){var r=DomUtils.h.createDiv(),n=(r.className="import-data-actions",DomUtils.h.createDiv()),a=(n.className="import-data-file-summary",n.textContent=a,r.appendChild(n),DomUtils.h.createDiv()),n=(a.className="import-data-action-buttons",DomUtils.h.createButton()),i=(n.className="btn btn-secondary",n.textContent="Clear All",n.disabled=!e,n.addEventListener("click",i),DomUtils.h.createButton());return i.className="btn btn-primary",i.textContent="Import Files",i.disabled=!e,i.addEventListener("click",t),a.appendChild(n),a.appendChild(i),r.appendChild(a),r}static _createFileItem(e,t){var i=DomUtils.h.createDiv(),a=(i.className="import-data-file-item",i.dataset.fileId=e.id,e.isSkipped&&i.classList.add("import-data-file-item-skipped"),DomUtils.h.createDiv()),r=(a.className="import-data-file-info",DomUtils.h.createDiv()),r=(r.className="import-data-file-name",e.isSkipped&&r.classList.add("import-data-file-name-skipped"),r.textContent=e.name,a.appendChild(r),DomUtils.h.createDiv()),r=(r.className="import-data-file-size",r.textContent=FileUtils.formatFileSize(e.size),a.appendChild(r),DomUtils.h.createDiv());r.className="import-data-file-status-container";let n="",l="";e.isSkipped?(n="error",l="Skipped"):e.isDuplicate?(n="warning",l="Renamed"):e.isTextFile||(n="error",l="Binary file"),l&&((o=DomUtils.h.createDiv()).className="import-data-file-status "+n,o.textContent=l,r.appendChild(o));var o=DomUtils.h.createButton();return o.className="import-data-remove-file-btn",o.textContent="×",o.addEventListener("click",()=>t(e.id)),r.appendChild(o),i.appendChild(a),i.appendChild(r),i}}module.exports=UIComponents;
